export const styles = {
  Root: "h-full w-full p-3 min-h-0",
  Column: "h-full min-h-0 flex flex-col gap-3 relative",
  Top: "flex-1 min-h-0",
  KnobPanel: "min-h-0",

  BusCardAreaRoot: "h-full min-h-0 flex gap-3",
  BusCardAreaMain: "flex-1 min-w-0 min-h-0",
  BusMenuBar: "w-[122px] shrink-0 min-h-0 flex flex-col gap-3",
  BusMenuButtonBase: "flex-1 min-h-0 w-full rounded-2xl border text-[14px] font-semibold tracking-wide transition shadow-[0_0_18px_rgba(0,0,0,0.45)]",
  BusMenuButtonActive: "border-green-400/70 bg-green-400/10 text-green-100 ring-2 ring-green-400/55 shadow-[0_0_22px_rgba(74,222,128,0.18)]",
  BusMenuButtonIdle: "border-white/10 bg-white/[0.06] text-white/70 hover:border-white/20 hover:bg-white/[0.10]",
  BusCardButton: "h-full min-h-0 text-left relative overflow-hidden",
  BusCardInnerRow: "h-full min-h-0 flex gap-4 items-center px-3",
  BusCardSideMeter: "shrink-0 flex items-center",
  BusCardLeft: "flex-1 min-w-0 min-h-0 flex flex-col justify-center gap-2",
  BusCardHeader: "absolute left-6 right-6 top-5 z-10 grid grid-cols-[1fr_auto] items-center gap-2",
  BusCardMapButton: "h-8 w-8 rounded-md border border-white/15 bg-white/10 hover:bg-white/20 active:bg-white/25 flex items-center justify-center cursor-grab active:cursor-grabbing",
  BusCardTitle: "text-[32px] leading-none font-semibold tracking-wide",
  BusCardModeBadgeBase: "inline-flex items-center px-2.5 py-1 rounded-full border text-[11px] leading-none",
  BusCardModeBadgeLinear: "bg-white/10 text-white/75 border-white/15",
  BusCardModeBadgeParallel: "bg-yellow-400/15 text-yellow-200 border-yellow-400/25",
  BusCardModeBadgeLcr: "bg-blue-400/15 text-blue-200 border-blue-400/25",
  BusCardRoutingSlot: "min-h-0",
  BusCardTrackGrid: "min-h-0 grid grid-cols-[repeat(3,minmax(280px,1fr))] gap-6 items-center justify-between",
  
  // RoutingWell
  RoutingWellRoot: "h-full min-h-0 p-3 flex flex-col gap-2",
  RoutingWellHeader: "flex items-center justify-between",
  RoutingWellTitle: "text-[11px] font-semibold tracking-wide text-white/70",
  RoutingWellFooter: "pt-1 text-[10px] text-white/35",
  ModeBadge: "text-[10px] px-2 py-0.5 rounded-full bg-white/10 border border-white/10 text-white/70",
  LanePillBase: "flex items-center justify-between px-2 py-1 rounded-lg border min-w-0",
  LanePillOn: "bg-white/10 border-white/15",
  LanePillOff: "bg-black/20 border-white/5 opacity-45",
  LanePillActiveRing: "ring-1 ring-green-400/40",
  LaneMapButton: "h-5 w-5 rounded border border-white/15 bg-white/10 hover:bg-white/20 active:bg-white/25 flex items-center justify-center cursor-grab active:cursor-grabbing",
  LaneStatePillBase: "text-[10px] px-2 py-0.5 rounded-full border",
  LaneStateOn: "bg-green-400/10 text-green-200 border-green-400/20",
  LaneStateOff: "bg-white/5 text-white/40 border-white/10",

  // PluginList (if you end up using it in Perform)
  PluginInset: "h-full min-h-0 p-2",
  PluginHeader: "flex items-center justify-between px-1 pb-2",
  PluginTitle: "text-[11px] font-semibold tracking-wide text-white/70",
  PluginCount: "text-[10px] text-white/35",
  PluginRows: "flex flex-col gap-1 min-h-0",
  PluginRowBase: "flex items-center gap-2 px-2 py-1.5 rounded-lg",
  PluginRowActive: "bg-white/10 border border-white/10",
  PluginRowIdle: "bg-white/0",
  PluginIndex: "w-5 text-[11px] opacity-60 tabular-nums",
  PluginName: "text-[12px] font-semibold leading-tight truncate",
  PluginVendor: "text-[11px] opacity-55 leading-tight truncate",
  PluginStateOn: "bg-green-400/10 text-green-200 border-green-400/20",
  PluginStateOff: "bg-white/5 text-white/40 border-white/10",
  
};

export const KNOB_STRIP_H = 185;
